```
TASK [kubernetes/node : Modprobe conntrack module] *********************************************************************
ok: [worker1] => (item=nf_conntrack) => {"ansible_loop_var": "item", "changed": false, "item": "nf_conntrack", "name": "nf_conntrack", "params": "", "state": "present"}
fatal: [worker1]: FAILED! => {"msg": "The conditional check '(modprobe_conntrack_module|default({'rc': 1})).rc != 0' failed. The error was: error while evaluating conditional ((modprobe_conntrack_module|default({'rc': 1})).rc != 0): 'dict object' has no attribute 'rc'. 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/home/user/kubespray/roles/kubernetes/node/tasks/main.yml': line 126, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Modprobe conntrack module\n  ^ here\n"}
...ignoring
ok: [worker2] => (item=nf_conntrack) => {"ansible_loop_var": "item", "changed": false, "item": "nf_conntrack", "name": "nf_conntrack", "params": "", "state": "present"}
fatal: [worker2]: FAILED! => {"msg": "The conditional check '(modprobe_conntrack_module|default({'rc': 1})).rc != 0' failed. The error was: error while evaluating conditional ((modprobe_conntrack_module|default({'rc': 1})).rc != 0): 'dict object' has no attribute 'rc'. 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/home/user/kubespray/roles/kubernetes/node/tasks/main.yml': line 126, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Modprobe conntrack module\n  ^ here\n"}
...ignoring
ok: [master] => (item=nf_conntrack) => {"ansible_loop_var": "item", "changed": false, "item": "nf_conntrack", "name": "nf_conntrack", "params": "", "state": "present"}
fatal: [master]: FAILED! => {"msg": "The conditional check '(modprobe_conntrack_module|default({'rc': 1})).rc != 0' failed. The error was: error while evaluating conditional ((modprobe_conntrack_module|default({'rc': 1})).rc != 0): 'dict object' has no attribute 'rc'. 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/home/user/kubespray/roles/kubernetes/node/tasks/main.yml': line 126, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Modprobe conntrack module\n  ^ here\n"}
...ignoring
ok: [worker4] => (item=nf_conntrack) => {"ansible_loop_var": "item", "changed": false, "item": "nf_conntrack", "name": "nf_conntrack", "params": "", "state": "present"}
fatal: [worker4]: FAILED! => {"msg": "The conditional check '(modprobe_conntrack_module|default({'rc': 1})).rc != 0' failed. The error was: error while evaluating conditional ((modprobe_conntrack_module|default({'rc': 1})).rc != 0): 'dict object' has no attribute 'rc'. 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/home/user/kubespray/roles/kubernetes/node/tasks/main.yml': line 126, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Modprobe conntrack module\n  ^ here\n"}
...ignoring
ok: [worker3] => (item=nf_conntrack) => {"ansible_loop_var": "item", "changed": false, "item": "nf_conntrack", "name": "nf_conntrack", "params": "", "state": "present"}
fatal: [worker3]: FAILED! => {"msg": "The conditional check '(modprobe_conntrack_module|default({'rc': 1})).rc != 0' failed. The error was: error while evaluating conditional ((modprobe_conntrack_module|default({'rc': 1})).rc != 0): 'dict object' has no attribute 'rc'. 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/home/user/kubespray/roles/kubernetes/node/tasks/main.yml': line 126, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Modprobe conntrack module\n  ^ here\n"}
...ignoring


TASK [kubernetes/control-plane : Check which kube-control nodes are already members of the cluster] ********************
fatal: [master]: FAILED! => {"changed": false, "cmd": ["/usr/local/bin/kubectl", "get", "nodes", "--selector=node-role.kubernetes.io/control-plane", "-o", "json"], "delta": "0:00:00.052337", "end": "2024-02-22 08:55:31.001499", "msg": "non-zero return code", "rc": 1, "start": "2024-02-22 08:55:30.949162", "stderr": "E0222 08:55:30.996023   36935 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0222 08:55:30.996256   36935 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0222 08:55:30.998175   36935 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0222 08:55:30.998438   36935 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nE0222 08:55:30.999567   36935 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused\nThe connection to the server localhost:8080 was refused - did you specify the right host or port?", "stderr_lines": ["E0222 08:55:30.996023   36935 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused", "E0222 08:55:30.996256   36935 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused", "E0222 08:55:30.998175   36935 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused", "E0222 08:55:30.998438   36935 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused", "E0222 08:55:30.999567   36935 memcache.go:265] couldn't get current server API group list: Get \"http://localhost:8080/api?timeout=32s\": dial tcp 127.0.0.1:8080: connect: connection refused", "The connection to the server localhost:8080 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}
...ignoring


TASK [kubernetes/control-plane : Kubeadm | Create kubeadm config] ******************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleError: An unhandled exception occurred while templating '{{ lookup('password', credentials_dir + '/kubeadm_certificate_key.creds length=64 chars=hexdigits') | lower }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'password'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unable to create local directories(/home/user/kubespray/inventory/mycluster/credentials): [Errno 13] Permission denied: b'/home/user/kubespray/inventory/mycluster/credentials'. Unable to create local directories(/home/user/kubespray/inventory/mycluster/credentials): [Errno 13] Permission denied: b'/home/user/kubespray/inventory/mycluster/credentials'
fatal: [master]: FAILED! => {"changed": false, "msg": "AnsibleError: An unhandled exception occurred while templating '{{ lookup('password', credentials_dir + '/kubeadm_certificate_key.creds length=64 chars=hexdigits') | lower }}'. Error was a <class 'ansible.errors.AnsibleError'>, original message: An unhandled exception occurred while running the lookup plugin 'password'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Unable to create local directories(/home/user/kubespray/inventory/mycluster/credentials): [Errno 13] Permission denied: b'/home/user/kubespray/inventory/mycluster/credentials'. Unable to create local directories(/home/user/kubespray/inventory/mycluster/credentials): [Errno 13] Permission denied: b'/home/user/kubespray/inventory/mycluster/credentials'"}

NO MORE HOSTS LEFT *****************************************************************************************************

PLAY RECAP *************************************************************************************************************
master                     : ok=521  changed=8    unreachable=0    failed=1    skipped=646  rescued=0    ignored=2
worker1                    : ok=360  changed=1    unreachable=0    failed=0    skipped=449  rescued=0    ignored=1
worker2                    : ok=360  changed=1    unreachable=0    failed=0    skipped=445  rescued=0    ignored=1
worker3                    : ok=360  changed=1    unreachable=0    failed=0    skipped=445  rescued=0    ignored=1
worker4                    : ok=360  changed=1    unreachable=0    failed=0    skipped=445  rescued=0    ignored=1

````